seed: 42

data:
  loader:
    batch_size: 4
    num_workers: 0
    pin_memory: false

model:
  in_channels: 2
  out_channels: 2
  num_timesteps: 1000
  schedule: linear
  unet:
    dim: 48
    dim_mults: [1, 2, 4, 8]
    channels: 4 #  in_channels * 2 
    out_dim: 2 # == out_channels

optimization:
  lr: 0.0001
  reduce_lr_on_plateau:
    factor: 0.5
    patience: 10

trainer:
  max_epochs: 100
  accelerator: auto
  devices: 1
  precision: 32
  log_every_n_steps: 10
  enable_checkpointing: false

logging:
  wandb:
    project: dif_img_rec
    name: null
    save_dir: logs
    log_model: false
